# @package _global_
dataset_path: /media/philipp/honeycomb/cAMP/20180705/20180705_exp_1.nd2
classifier: /home/philipp/PycharmProjects/classifiers/20180705_exp_1_channel_0_2_classifier_3_classes
frames: all
positions: all
channels_to_segment: [0, 2]
return_channels_together: True