dataset_path: /media/philipp/honeycomb/cAMP/20180705/20180705_exp_1.nd2
classifier: ???
frames: 0
positions: 0
z_levels: 1
channels_to_segment: 0
return_channels_together: True # only implemented for ND2 stacks!
normalise_img: False
