dataset_path: /media/philipp/honeycomb/20210224/20210224_exp_9.nd2
classifier: /home/philipp/PycharmProjects/classifiers/20210224_exp_9_channel_1_rf_classifier_3_classes
frames: all
positions: all
z_levels: all
channels_to_segment: [0, 1]
return_channels_together: True
normalise_img: False